# Generated by Django 5.1.1 on 2024-09-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seat', '0005_seat_bus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='bus',
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
